# Baseline capacity
apiVersion: karpenter.sh/v1alpha5
kind: NodeGroup
metadata:
  name: default
spec:
  replicas: 5
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
      - m5.large
    - key: karpenter.sh/capacity-type
      operator: In
      values:
      - on-demand
  provider:
    securityGroupSelector:
      kubernetes.io/cluster/etarn: '*'
    subnetSelector:
      kubernetes.io/cluster/etarn: '*'
---
# Dynamically provision capacity for pending pods
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.sh/capacity-type
      operator: In
      values:
      - spot
  provider:
    securityGroupSelector:
      kubernetes.io/cluster/etarn: '*'
    subnetSelector:
      kubernetes.io/cluster/etarn: '*'
