name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          k8sVersion: ["1.19.x", "1.20.x", "1.21.x", "1.22.x"]
    env:
      K8S_VERSION: ${{ matrix.k8sVersion }}
    steps:
    - uses: actions/checkout@v2
    - run: sed -En 's/^go[[:space:]]+([[:digit:].]+)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/go/bin/
          ~/.kubebuilder/bin/k8s
        key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
    - name: CI - Verifications and Tests
      run: |
        make ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
