name: Deflake
on:
  schedule:
    - cron: '0 12 * * *'
jobs:
  deflake:
    if: github.repository == 'aws/karpenter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sed -En 's/^go[[:space:]]+([[:digit:].]+)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin/
            ~/.kubebuilder/bin/k8s
          key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
      - name: Running tests 10 times to find flaky tests
        run: |
          make toolchain
          make deflake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
