name: SnapshotsONPRs
on:
  pull_request_review:
    types: [ submitted ]
permissions:
  id-token: write
  contents: read
jobs:
  snapshotsOnPRs:
    permissions:
      id-token: write
      contents: read
    if: github.repository == 'aws/karpenter' && github.event.review.state == 'approved' && startsWith(github.event.review.body, '/snapshot')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sed -En 's/^go[[:space:]]+([[:digit:].]+)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin/
            ~/.kubebuilder/bin/k8s
          key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::274912145732:role/Snapshots
          aws-region: us-east-1
      - run: make toolchain
      - run: make snapshot
        env:
          CLOUD_PROVIDER: aws
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let fs = require('fs');
            let issue_number = Number(fs.readFileSync('./pr_number'));
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: 'Snapshot release created.'
            });
